### ISSUE TITLE
请问ro.ril.oem.imei这个值是怎么来的

### ISSUE THREAD

**Issue by wuliao6688** [RinGotou/Polaris_IMEI_Patch#2]
我搜索了AOSP的源码并没有发现有这个相关代码

**Comment by RinGotou** [comment]
根据之前别人的讨论, 这个值是小米自己添加的(其他一部分厂商也有类似行为但是我没有机器无法确认), 而且是在启动中多次尝试写入这个值, 所以我才尝试制作了这个模块强行在启动时把对应的值覆盖掉.
目前我没法确认到底是哪个组件写入了这一些值,

**Comment by wuliao6688** [comment]
你这个模快 是并入到kernel里去吗  在init.rc里启用它是吗  可否给个示例

**Comment by RinGotou** [comment]
并不是, 我的模块只是一个magisk module, 在机器上已经刷写了magisk的情况之下安装模块, 利用其提供的开机加载阶段脚本执行的能力不断尝试setprop覆盖由小米的组件生成的值而已, 并没有对机器的kernel做任何修改(本人没有Android固件开发经验).
但是根据目前我所知道的情况, 在基于Android 9的MIUI上, 在正常启用SELinux的时候这几个值是无法被直接访问的, 只有设置为permissive的情况下可以被任意读取, 但是在基于Android 10的固件上无论SELinux状态如何都能被任意访问. 我常年使用LineageOS, 之前我的试验是无论Android版本如何都可被任意访问. 而且, 不同机型在不同Android版本下的可访问性也有差别.
你可以尝试一下对SEPolicy进行修改来使这些值无法被任意访问, 我没有Linux kernel的开发经验暂时帮不上什么忙, 抱歉

**Comment by wuliao6688** [comment]
感谢你的  帮助  如果在我kernel里解决了这个问题  我会分享给你
